# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: none

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Automatic Formatting
      run: |
        # run yapf to format the scripts automatically
        yapf -i --style '{use_tabs: False}' ./StockIntelligence/get_stock_data.py
        yapf -i --style '{use_tabs: False}' ./StockIntelligence/load_stock_data.py
        yapf -i ./setup.py
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82,E111 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: run pytest
      run: |
        pip install lxml
        pip install git+https://github.com/zhenxiay/StockIntelligence.git@test
        pytest tests/
